### ISSUE TITLE
Howto remove quality 720p and 1080p

### ISSUE THREAD

**Issue by fadeldamen** [niphlod/w2p_tvseries#17]
I have  put NO_720p in Quality field but now I like remove 1080p series, and put "NO_720p, NO_1080p" do no work.

how should I do ?

**Comment by niphlod** [comment]
uhm. it should work. @fadeldamen : did you try with "NO_720p,NO_1080p" instead of leaving a space between the two ?

**Comment by fadeldamen** [comment]
yes thanks Its Works fine.
